from __future__ import annotations

DATASET_VERSION = "2026.08"

CATALOG = [
    {
        "code": "9403",
        "kind": "HSN",
        "name": "Office furniture",
        "aliases": ["office furniture", "chairs", "desks", "tables", "workstation"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule III",
        "chapter": "94",
        "heading": "9403",
        "subheading": "",
        "technical_description": "Other furniture and parts thereof",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "8471",
        "kind": "HSN",
        "name": "Computers and laptops",
        "aliases": ["computers", "laptops", "peripherals", "pc", "desktop"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule III",
        "chapter": "84",
        "heading": "8471",
        "subheading": "",
        "technical_description": "Automatic data processing machines and units thereof",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "84716040",
        "kind": "HSN",
        "name": "Laptop",
        "aliases": ["laptop", "notebook"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule III",
        "chapter": "84",
        "heading": "8471",
        "subheading": "847160",
        "technical_description": "Automatic data processing machines - laptop",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "8517",
        "kind": "HSN",
        "name": "Smartphones and networking routers",
        "aliases": ["smartphones", "networking routers", "mobile", "router", "switch"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule III",
        "chapter": "85",
        "heading": "8517",
        "subheading": "",
        "technical_description": "Telephone sets, including smartphones",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "8703",
        "kind": "HSN",
        "name": "Motor cars and passenger vehicles",
        "aliases": ["motor cars", "passenger vehicles", "car", "suv"],
        "rate": 28.0,
        "itc": False,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule IV",
        "chapter": "87",
        "heading": "8703",
        "subheading": "",
        "technical_description": "Motor cars and other motor vehicles principally designed for the transport of persons",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 22.0,
        "rcm_applicable": False,
        "blocked_reason": "Section 17(5)(a)"
    },
    {
        "code": "2106",
        "kind": "HSN",
        "name": "Food, catering and restaurant",
        "aliases": ["food", "catering", "restaurant", "meal"],
        "rate": 5.0,
        "itc": False,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule I",
        "chapter": "21",
        "heading": "2106",
        "subheading": "",
        "technical_description": "Food preparations not elsewhere specified or included",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "Section 17(5)(b)"
    },
    {
        "code": "2501",
        "kind": "HSN",
        "name": "Cement (Portland)",
        "aliases": ["cement", "portland", "construction material"],
        "rate": 28.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule IV",
        "chapter": "25",
        "heading": "2501",
        "subheading": "",
        "technical_description": "Salt (including table salt and denatured salt)",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "7210",
        "kind": "HSN",
        "name": "Steel",
        "aliases": ["steel", "flat rolled", "coated"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule III",
        "chapter": "72",
        "heading": "7210",
        "subheading": "",
        "technical_description": "Flat-rolled products of iron or non-alloy steel",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "3004",
        "kind": "HSN",
        "name": "Medicines",
        "aliases": ["medicines", "pharmaceutical preparations", "drugs", "pharma"],
        "rate": 12.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule II",
        "chapter": "30",
        "heading": "3004",
        "subheading": "",
        "technical_description": "Medicaments consisting of mixed or unmixed products",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "6204",
        "kind": "HSN",
        "name": "Women's garments",
        "aliases": ["women's garments", "clothing", "apparel"],
        "rate": 12.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule II",
        "chapter": "62",
        "heading": "6204",
        "subheading": "",
        "technical_description": "Women's or girls' suits, ensembles",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "6403",
        "kind": "HSN",
        "name": "Footwear",
        "aliases": ["footwear", "shoes", "boots"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule III",
        "chapter": "64",
        "heading": "6403",
        "subheading": "",
        "technical_description": "Footwear with outer soles of rubber",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "8415",
        "kind": "HSN",
        "name": "Air conditioners",
        "aliases": ["air conditioners", "ac", "cooling"],
        "rate": 28.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule IV",
        "chapter": "84",
        "heading": "8415",
        "subheading": "",
        "technical_description": "Air conditioning machines",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "8528",
        "kind": "HSN",
        "name": "Televisions and monitors",
        "aliases": ["televisions", "monitors", "tv", "screen"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule III",
        "chapter": "85",
        "heading": "8528",
        "subheading": "",
        "technical_description": "Monitors and projectors",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "4901",
        "kind": "HSN",
        "name": "Books and printed matter",
        "aliases": ["books", "printed matter", "reading", "novel"],
        "rate": 0.0,
        "itc": False,
        "source": "Notification No. 02/2017-Central Tax (Rate)",
        "chapter": "49",
        "heading": "4901",
        "subheading": "",
        "technical_description": "Printed books, brochures",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "998313",
        "kind": "SAC",
        "name": "IT and Software development services",
        "aliases": ["it", "software development", "programming", "coding", "software"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 11/2017-Central Tax (Rate)",
        "chapter": "99",
        "heading": "9983",
        "subheading": "998313",
        "technical_description": "Information technology (IT) consulting and support services",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "998314",
        "kind": "SAC",
        "name": "Web hosting and UI/UX design",
        "aliases": ["web hosting", "ui/ux design", "hosting", "design", "website"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 11/2017-Central Tax (Rate)",
        "chapter": "99",
        "heading": "9983",
        "subheading": "998314",
        "technical_description": "Information technology (IT) design and development services",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "998221",
        "kind": "SAC",
        "name": "Accounting, tax audit, bookkeeping",
        "aliases": ["accounting", "tax audit", "bookkeeping", "ca", "audit"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 11/2017-Central Tax (Rate)",
        "chapter": "99",
        "heading": "9982",
        "subheading": "998221",
        "technical_description": "Financial auditing services",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "998231",
        "kind": "SAC",
        "name": "Legal advisory services",
        "aliases": ["legal advisory", "lawyer", "advocate", "legal"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 11/2017-Central Tax (Rate)",
        "chapter": "99",
        "heading": "9982",
        "subheading": "998231",
        "technical_description": "Legal advisory and representation services",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "996511",
        "kind": "SAC",
        "name": "Goods transport agency (GTA)",
        "aliases": ["goods transport agency", "gta", "transport", "freight", "logistics"],
        "rate": 5.0,
        "itc": False,
        "source": "Notification No. 11/2017-Central Tax (Rate)",
        "chapter": "99",
        "heading": "9965",
        "subheading": "996511",
        "technical_description": "Road transport services of goods",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": True,
        "blocked_reason": "ITC conditional on GTA rate selection"
    },
    {
        "code": "996312",
        "kind": "SAC",
        "name": "Renting of residential dwelling",
        "aliases": ["renting", "residential dwelling", "rent", "apartment", "house"],
        "rate": 0.0,
        "itc": False,
        "source": "Notification No. 12/2017-Central Tax (Rate)",
        "chapter": "99",
        "heading": "9963",
        "subheading": "996312",
        "technical_description": "Leasing or rental services concerning residential real estate",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "997212",
        "kind": "SAC",
        "name": "Construction of residential complex",
        "aliases": ["construction", "residential complex", "builder", "real estate"],
        "rate": 5.0,
        "itc": False,
        "source": "Notification No. 11/2017-Central Tax (Rate)",
        "chapter": "99",
        "heading": "9972",
        "subheading": "997212",
        "technical_description": "Construction services of residential buildings",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "998411",
        "kind": "SAC",
        "name": "Advertising services",
        "aliases": ["advertising", "marketing", "ads", "promotion"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 11/2017-Central Tax (Rate)",
        "chapter": "99",
        "heading": "9984",
        "subheading": "998411",
        "technical_description": "Sale of advertising space in print media",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    },
    {
        "code": "995411",
        "kind": "SAC",
        "name": "Cleaning and maintenance services",
        "aliases": ["cleaning", "maintenance", "housekeeping", "janitorial"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 11/2017-Central Tax (Rate)",
        "chapter": "99",
        "heading": "9954",
        "subheading": "995411",
        "technical_description": "General cleaning services",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": ""
    }
]

def find_candidates(text: str) -> list[dict]:
    """Score catalog items against natural language text. Return sorted by relevance."""
    q = text.lower()
    scored = []
    for item in CATALOG:
        score = sum(1 for token in item["aliases"] if token in q)
        if score:
            scored.append((score, item))
    return [item for _, item in sorted(scored, key=lambda x: x[0], reverse=True)]

def by_code(code: str) -> dict | None:
    """Direct lookup by HSN or SAC code."""
    return next((item for item in CATALOG if item["code"] == code), None)
